-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-05-25 04:44:30.109

-- foreign keys
ALTER TABLE SAPNU_PUAS.Auto DROP CONSTRAINT Auto_Chofer;

ALTER TABLE SAPNU_PUAS.Auto DROP CONSTRAINT Auto_Marca;

ALTER TABLE SAPNU_PUAS.Auto DROP CONSTRAINT Auto_Turno;

ALTER TABLE SAPNU_PUAS.Chofer DROP CONSTRAINT Chofer_Persona;

ALTER TABLE SAPNU_PUAS.Cliente DROP CONSTRAINT Cliente_Persona;

ALTER TABLE SAPNU_PUAS.Factura DROP CONSTRAINT Factura_Cliente;

ALTER TABLE SAPNU_PUAS.Funcionalidad_x_Rol DROP CONSTRAINT Funcionalidad_x_Rol_Funcionalidad;

ALTER TABLE SAPNU_PUAS.Funcionalidad_x_Rol DROP CONSTRAINT Funcionalidad_x_Rol_Rol;

ALTER TABLE SAPNU_PUAS.Persona DROP CONSTRAINT Persona_Usuario;

ALTER TABLE SAPNU_PUAS.Rendicion DROP CONSTRAINT Rendicion_Chofer;

ALTER TABLE SAPNU_PUAS.Rendicion DROP CONSTRAINT Rendicion_Turno;

ALTER TABLE SAPNU_PUAS.Rol_x_Usuario DROP CONSTRAINT Rol_x_Usuario_Rol;

ALTER TABLE SAPNU_PUAS.Rol_x_Usuario DROP CONSTRAINT Rol_x_Usuario_Usuario;

ALTER TABLE SAPNU_PUAS.Viaje DROP CONSTRAINT Viaje_Auto;

ALTER TABLE SAPNU_PUAS.Viaje DROP CONSTRAINT Viaje_Chofer;

ALTER TABLE SAPNU_PUAS.Viaje DROP CONSTRAINT Viaje_Cliente;

ALTER TABLE SAPNU_PUAS.Viaje DROP CONSTRAINT Viaje_Turno;

ALTER TABLE SAPNU_PUAS.Viaje_x_Factura DROP CONSTRAINT Viaje_x_Factura_Factura;

ALTER TABLE SAPNU_PUAS.Viaje_x_Factura DROP CONSTRAINT Viaje_x_Factura_Viaje;

ALTER TABLE SAPNU_PUAS.Viaje_x_Rendicion DROP CONSTRAINT Viaje_x_Rendicion_Rendicion;

ALTER TABLE SAPNU_PUAS.Viaje_x_Rendicion DROP CONSTRAINT Viaje_x_Rendicion_Viaje;

-- tables
DROP TABLE SAPNU_PUAS.Auto;

DROP TABLE SAPNU_PUAS.Chofer;

DROP TABLE SAPNU_PUAS.Cliente;

DROP TABLE SAPNU_PUAS.Factura;

DROP TABLE SAPNU_PUAS.Funcionalidad;

DROP TABLE SAPNU_PUAS.Funcionalidad_x_Rol;

DROP TABLE SAPNU_PUAS.Marca;

DROP TABLE SAPNU_PUAS.Persona;

DROP TABLE SAPNU_PUAS.Rendicion;

DROP TABLE SAPNU_PUAS.Rol;

DROP TABLE SAPNU_PUAS.Rol_x_Usuario;

DROP TABLE SAPNU_PUAS.Turno;

DROP TABLE SAPNU_PUAS.Usuario;

DROP TABLE SAPNU_PUAS.Viaje;

DROP TABLE SAPNU_PUAS.Viaje_x_Factura;

DROP TABLE SAPNU_PUAS.Viaje_x_Rendicion;

-- End of file.

